name: Heroku Deploy

on:
    push:
        branches: [main]

jobs:
    heroku-deploy:
        name: Backend Build, Heroku Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2

            # Setup Heroku Deploy
            - name: Build, Push, and Deploy Backend Container
              uses: akhileshns/heroku-deploy@v3.12.12
              with:
                heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
                heroku_email: ${{ secrets.HEROKU_EMAIL }}
                usedocker: true
